# conda env create -f environment.yml
name: ahr_tead_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    # python version
    - python=3.8.3

    # conda packages
    - pandas=1.3.5
    - seaborn=0.11.2
    - jupyterlab=3.2.5